// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package condition

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheStorage creates a new instance of MockCacheStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheStorage[V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheStorage[V] {
	mock := &MockCacheStorage[V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheStorage is an autogenerated mock type for the CacheStorage type
type MockCacheStorage[V any] struct {
	mock.Mock
}

type MockCacheStorage_Expecter[V any] struct {
	mock *mock.Mock
}

func (_m *MockCacheStorage[V]) EXPECT() *MockCacheStorage_Expecter[V] {
	return &MockCacheStorage_Expecter[V]{mock: &_m.Mock}
}

// Get provides a mock function for the type MockCacheStorage
func (_mock *MockCacheStorage[V]) Get(ctx context.Context, key string) (V, bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 V
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (V, bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) V); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCacheStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheStorage_Get_Call[V any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheStorage_Expecter[V]) Get(ctx any, key any) *MockCacheStorage_Get_Call[V] {
	return &MockCacheStorage_Get_Call[V]{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockCacheStorage_Get_Call[V]) Run(run func(ctx context.Context, key string)) *MockCacheStorage_Get_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheStorage_Get_Call[V]) Return(value V, ok bool, err error) *MockCacheStorage_Get_Call[V] {
	_c.Call.Return(value, ok, err)
	return _c
}

func (_c *MockCacheStorage_Get_Call[V]) RunAndReturn(run func(ctx context.Context, key string) (V, bool, error)) *MockCacheStorage_Get_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCacheStorage
func (_mock *MockCacheStorage[V]) Set(ctx context.Context, key string, ttl time.Duration, value V) error {
	ret := _mock.Called(ctx, key, ttl, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, V) error); ok {
		r0 = returnFunc(ctx, key, ttl, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheStorage_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCacheStorage_Set_Call[V any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
//   - value V
func (_e *MockCacheStorage_Expecter[V]) Set(ctx any, key any, ttl any, value any) *MockCacheStorage_Set_Call[V] {
	return &MockCacheStorage_Set_Call[V]{Call: _e.mock.On("Set", ctx, key, ttl, value)}
}

func (_c *MockCacheStorage_Set_Call[V]) Run(run func(ctx context.Context, key string, ttl time.Duration, value V)) *MockCacheStorage_Set_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 V
		if args[3] != nil {
			arg3 = args[3].(V)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCacheStorage_Set_Call[V]) Return(err error) *MockCacheStorage_Set_Call[V] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheStorage_Set_Call[V]) RunAndReturn(run func(ctx context.Context, key string, ttl time.Duration, value V) error) *MockCacheStorage_Set_Call[V] {
	_c.Call.Return(run)
	return _c
}
