// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package firehose

import (
	"context"

	"github.com/emad-elsaid/boolexpr"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource[T] {
	mock := &MockSource[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource[T any] struct {
	mock.Mock
}

type MockSource_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockSource[T]) EXPECT() *MockSource_Expecter[T] {
	return &MockSource_Expecter[T]{mock: &_m.Mock}
}

// Start provides a mock function for the type MockSource
func (_mock *MockSource[T]) Start(ctx context.Context, cb Callback[T]) (<-chan struct{}, error) {
	ret := _mock.Called(ctx, cb)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 <-chan struct{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Callback[T]) (<-chan struct{}, error)); ok {
		return returnFunc(ctx, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Callback[T]) <-chan struct{}); ok {
		r0 = returnFunc(ctx, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Callback[T]) error); ok {
		r1 = returnFunc(ctx, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSource_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockSource_Start_Call[T any] struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - cb Callback[T]
func (_e *MockSource_Expecter[T]) Start(ctx any, cb any) *MockSource_Start_Call[T] {
	return &MockSource_Start_Call[T]{Call: _e.mock.On("Start", ctx, cb)}
}

func (_c *MockSource_Start_Call[T]) Run(run func(ctx context.Context, cb Callback[T])) *MockSource_Start_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Callback[T]
		if args[1] != nil {
			arg1 = args[1].(Callback[T])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSource_Start_Call[T]) Return(done <-chan struct{}, err error) *MockSource_Start_Call[T] {
	_c.Call.Return(done, err)
	return _c
}

func (_c *MockSource_Start_Call[T]) RunAndReturn(run func(ctx context.Context, cb Callback[T]) (<-chan struct{}, error)) *MockSource_Start_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockAction creates a new instance of MockAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAction[I any, O any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAction[I, O] {
	mock := &MockAction[I, O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAction is an autogenerated mock type for the Action type
type MockAction[I any, O any] struct {
	mock.Mock
}

type MockAction_Expecter[I any, O any] struct {
	mock *mock.Mock
}

func (_m *MockAction[I, O]) EXPECT() *MockAction_Expecter[I, O] {
	return &MockAction_Expecter[I, O]{mock: &_m.Mock}
}

// Process provides a mock function for the type MockAction
func (_mock *MockAction[I, O]) Process(ctx context.Context, event I, syms boolexpr.Symbols) (O, error) {
	ret := _mock.Called(ctx, event, syms)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 O
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, I, boolexpr.Symbols) (O, error)); ok {
		return returnFunc(ctx, event, syms)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, I, boolexpr.Symbols) O); ok {
		r0 = returnFunc(ctx, event, syms)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(O)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, I, boolexpr.Symbols) error); ok {
		r1 = returnFunc(ctx, event, syms)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAction_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockAction_Process_Call[I any, O any] struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - event I
//   - syms boolexpr.Symbols
func (_e *MockAction_Expecter[I, O]) Process(ctx any, event any, syms any) *MockAction_Process_Call[I, O] {
	return &MockAction_Process_Call[I, O]{Call: _e.mock.On("Process", ctx, event, syms)}
}

func (_c *MockAction_Process_Call[I, O]) Run(run func(ctx context.Context, event I, syms boolexpr.Symbols)) *MockAction_Process_Call[I, O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 I
		if args[1] != nil {
			arg1 = args[1].(I)
		}
		var arg2 boolexpr.Symbols
		if args[2] != nil {
			arg2 = args[2].(boolexpr.Symbols)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAction_Process_Call[I, O]) Return(v O, err error) *MockAction_Process_Call[I, O] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAction_Process_Call[I, O]) RunAndReturn(run func(ctx context.Context, event I, syms boolexpr.Symbols) (O, error)) *MockAction_Process_Call[I, O] {
	_c.Call.Return(run)
	return _c
}

// NewMockDestination creates a new instance of MockDestination. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDestination[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDestination[T] {
	mock := &MockDestination[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDestination is an autogenerated mock type for the Destination type
type MockDestination[T any] struct {
	mock.Mock
}

type MockDestination_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockDestination[T]) EXPECT() *MockDestination_Expecter[T] {
	return &MockDestination_Expecter[T]{mock: &_m.Mock}
}

// Send provides a mock function for the type MockDestination
func (_mock *MockDestination[T]) Send(ctx context.Context, event T) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDestination_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockDestination_Send_Call[T any] struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - event T
func (_e *MockDestination_Expecter[T]) Send(ctx any, event any) *MockDestination_Send_Call[T] {
	return &MockDestination_Send_Call[T]{Call: _e.mock.On("Send", ctx, event)}
}

func (_c *MockDestination_Send_Call[T]) Run(run func(ctx context.Context, event T)) *MockDestination_Send_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDestination_Send_Call[T]) Return(err error) *MockDestination_Send_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDestination_Send_Call[T]) RunAndReturn(run func(ctx context.Context, event T) error) *MockDestination_Send_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockCondition creates a new instance of MockCondition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCondition[I any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCondition[I] {
	mock := &MockCondition[I]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCondition is an autogenerated mock type for the Condition type
type MockCondition[I any] struct {
	mock.Mock
}

type MockCondition_Expecter[I any] struct {
	mock *mock.Mock
}

func (_m *MockCondition[I]) EXPECT() *MockCondition_Expecter[I] {
	return &MockCondition_Expecter[I]{mock: &_m.Mock}
}

// Evaluate provides a mock function for the type MockCondition
func (_mock *MockCondition[I]) Evaluate(ctx context.Context, event I, syms boolexpr.Symbols) (bool, error) {
	ret := _mock.Called(ctx, event, syms)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, I, boolexpr.Symbols) (bool, error)); ok {
		return returnFunc(ctx, event, syms)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, I, boolexpr.Symbols) bool); ok {
		r0 = returnFunc(ctx, event, syms)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, I, boolexpr.Symbols) error); ok {
		r1 = returnFunc(ctx, event, syms)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCondition_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type MockCondition_Evaluate_Call[I any] struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - event I
//   - syms boolexpr.Symbols
func (_e *MockCondition_Expecter[I]) Evaluate(ctx any, event any, syms any) *MockCondition_Evaluate_Call[I] {
	return &MockCondition_Evaluate_Call[I]{Call: _e.mock.On("Evaluate", ctx, event, syms)}
}

func (_c *MockCondition_Evaluate_Call[I]) Run(run func(ctx context.Context, event I, syms boolexpr.Symbols)) *MockCondition_Evaluate_Call[I] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 I
		if args[1] != nil {
			arg1 = args[1].(I)
		}
		var arg2 boolexpr.Symbols
		if args[2] != nil {
			arg2 = args[2].(boolexpr.Symbols)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCondition_Evaluate_Call[I]) Return(b bool, err error) *MockCondition_Evaluate_Call[I] {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockCondition_Evaluate_Call[I]) RunAndReturn(run func(ctx context.Context, event I, syms boolexpr.Symbols) (bool, error)) *MockCondition_Evaluate_Call[I] {
	_c.Call.Return(run)
	return _c
}

// NewMockRule creates a new instance of MockRule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRule {
	mock := &MockRule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRule is an autogenerated mock type for the Rule type
type MockRule struct {
	mock.Mock
}

type MockRule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRule) EXPECT() *MockRule_Expecter {
	return &MockRule_Expecter{mock: &_m.Mock}
}

// GetEnvironments provides a mock function for the type MockRule
func (_mock *MockRule) GetEnvironments() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEnvironments")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockRule_GetEnvironments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnvironments'
type MockRule_GetEnvironments_Call struct {
	*mock.Call
}

// GetEnvironments is a helper method to define mock.On call
func (_e *MockRule_Expecter) GetEnvironments() *MockRule_GetEnvironments_Call {
	return &MockRule_GetEnvironments_Call{Call: _e.mock.On("GetEnvironments")}
}

func (_c *MockRule_GetEnvironments_Call) Run(run func()) *MockRule_GetEnvironments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRule_GetEnvironments_Call) Return(strings []string) *MockRule_GetEnvironments_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockRule_GetEnvironments_Call) RunAndReturn(run func() []string) *MockRule_GetEnvironments_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function for the type MockRule
func (_mock *MockRule) GetID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRule_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockRule_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockRule_Expecter) GetID() *MockRule_GetID_Call {
	return &MockRule_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockRule_GetID_Call) Run(run func()) *MockRule_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRule_GetID_Call) Return(s string) *MockRule_GetID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRule_GetID_Call) RunAndReturn(run func() string) *MockRule_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNext provides a mock function for the type MockRule
func (_mock *MockRule) GetNext() Rule {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNext")
	}

	var r0 Rule
	if returnFunc, ok := ret.Get(0).(func() Rule); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Rule)
		}
	}
	return r0
}

// MockRule_GetNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNext'
type MockRule_GetNext_Call struct {
	*mock.Call
}

// GetNext is a helper method to define mock.On call
func (_e *MockRule_Expecter) GetNext() *MockRule_GetNext_Call {
	return &MockRule_GetNext_Call{Call: _e.mock.On("GetNext")}
}

func (_c *MockRule_GetNext_Call) Run(run func()) *MockRule_GetNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRule_GetNext_Call) Return(rule Rule) *MockRule_GetNext_Call {
	_c.Call.Return(rule)
	return _c
}

func (_c *MockRule_GetNext_Call) RunAndReturn(run func() Rule) *MockRule_GetNext_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextSameSource provides a mock function for the type MockRule
func (_mock *MockRule) GetNextSameSource() Rule {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNextSameSource")
	}

	var r0 Rule
	if returnFunc, ok := ret.Get(0).(func() Rule); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Rule)
		}
	}
	return r0
}

// MockRule_GetNextSameSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextSameSource'
type MockRule_GetNextSameSource_Call struct {
	*mock.Call
}

// GetNextSameSource is a helper method to define mock.On call
func (_e *MockRule_Expecter) GetNextSameSource() *MockRule_GetNextSameSource_Call {
	return &MockRule_GetNextSameSource_Call{Call: _e.mock.On("GetNextSameSource")}
}

func (_c *MockRule_GetNextSameSource_Call) Run(run func()) *MockRule_GetNextSameSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRule_GetNextSameSource_Call) Return(rule Rule) *MockRule_GetNextSameSource_Call {
	_c.Call.Return(rule)
	return _c
}

func (_c *MockRule_GetNextSameSource_Call) RunAndReturn(run func() Rule) *MockRule_GetNextSameSource_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrev provides a mock function for the type MockRule
func (_mock *MockRule) GetPrev() Rule {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPrev")
	}

	var r0 Rule
	if returnFunc, ok := ret.Get(0).(func() Rule); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Rule)
		}
	}
	return r0
}

// MockRule_GetPrev_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrev'
type MockRule_GetPrev_Call struct {
	*mock.Call
}

// GetPrev is a helper method to define mock.On call
func (_e *MockRule_Expecter) GetPrev() *MockRule_GetPrev_Call {
	return &MockRule_GetPrev_Call{Call: _e.mock.On("GetPrev")}
}

func (_c *MockRule_GetPrev_Call) Run(run func()) *MockRule_GetPrev_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRule_GetPrev_Call) Return(rule Rule) *MockRule_GetPrev_Call {
	_c.Call.Return(rule)
	return _c
}

func (_c *MockRule_GetPrev_Call) RunAndReturn(run func() Rule) *MockRule_GetPrev_Call {
	_c.Call.Return(run)
	return _c
}

// GetSource provides a mock function for the type MockRule
func (_mock *MockRule) GetSource() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSource")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockRule_GetSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSource'
type MockRule_GetSource_Call struct {
	*mock.Call
}

// GetSource is a helper method to define mock.On call
func (_e *MockRule_Expecter) GetSource() *MockRule_GetSource_Call {
	return &MockRule_GetSource_Call{Call: _e.mock.On("GetSource")}
}

func (_c *MockRule_GetSource_Call) Run(run func()) *MockRule_GetSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRule_GetSource_Call) Return(v any) *MockRule_GetSource_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockRule_GetSource_Call) RunAndReturn(run func() any) *MockRule_GetSource_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockRule
func (_mock *MockRule) Init(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRule_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockRule_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRule_Expecter) Init(ctx any) *MockRule_Init_Call {
	return &MockRule_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockRule_Init_Call) Run(run func(ctx context.Context)) *MockRule_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRule_Init_Call) Return(err error) *MockRule_Init_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRule_Init_Call) RunAndReturn(run func(ctx context.Context) error) *MockRule_Init_Call {
	_c.Call.Return(run)
	return _c
}

// SetNext provides a mock function for the type MockRule
func (_mock *MockRule) SetNext(n Rule) {
	_mock.Called(n)
	return
}

// MockRule_SetNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNext'
type MockRule_SetNext_Call struct {
	*mock.Call
}

// SetNext is a helper method to define mock.On call
//   - n Rule
func (_e *MockRule_Expecter) SetNext(n any) *MockRule_SetNext_Call {
	return &MockRule_SetNext_Call{Call: _e.mock.On("SetNext", n)}
}

func (_c *MockRule_SetNext_Call) Run(run func(n Rule)) *MockRule_SetNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Rule
		if args[0] != nil {
			arg0 = args[0].(Rule)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRule_SetNext_Call) Return() *MockRule_SetNext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRule_SetNext_Call) RunAndReturn(run func(n Rule)) *MockRule_SetNext_Call {
	_c.Run(run)
	return _c
}

// SetNextSameSource provides a mock function for the type MockRule
func (_mock *MockRule) SetNextSameSource(n Rule) {
	_mock.Called(n)
	return
}

// MockRule_SetNextSameSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNextSameSource'
type MockRule_SetNextSameSource_Call struct {
	*mock.Call
}

// SetNextSameSource is a helper method to define mock.On call
//   - n Rule
func (_e *MockRule_Expecter) SetNextSameSource(n any) *MockRule_SetNextSameSource_Call {
	return &MockRule_SetNextSameSource_Call{Call: _e.mock.On("SetNextSameSource", n)}
}

func (_c *MockRule_SetNextSameSource_Call) Run(run func(n Rule)) *MockRule_SetNextSameSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Rule
		if args[0] != nil {
			arg0 = args[0].(Rule)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRule_SetNextSameSource_Call) Return() *MockRule_SetNextSameSource_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRule_SetNextSameSource_Call) RunAndReturn(run func(n Rule)) *MockRule_SetNextSameSource_Call {
	_c.Run(run)
	return _c
}

// SetPrev provides a mock function for the type MockRule
func (_mock *MockRule) SetPrev(p Rule) {
	_mock.Called(p)
	return
}

// MockRule_SetPrev_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPrev'
type MockRule_SetPrev_Call struct {
	*mock.Call
}

// SetPrev is a helper method to define mock.On call
//   - p Rule
func (_e *MockRule_Expecter) SetPrev(p any) *MockRule_SetPrev_Call {
	return &MockRule_SetPrev_Call{Call: _e.mock.On("SetPrev", p)}
}

func (_c *MockRule_SetPrev_Call) Run(run func(p Rule)) *MockRule_SetPrev_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Rule
		if args[0] != nil {
			arg0 = args[0].(Rule)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRule_SetPrev_Call) Return() *MockRule_SetPrev_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRule_SetPrev_Call) RunAndReturn(run func(p Rule)) *MockRule_SetPrev_Call {
	_c.Run(run)
	return _c
}

// SetPrevSameSource provides a mock function for the type MockRule
func (_mock *MockRule) SetPrevSameSource(p Rule) {
	_mock.Called(p)
	return
}

// MockRule_SetPrevSameSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPrevSameSource'
type MockRule_SetPrevSameSource_Call struct {
	*mock.Call
}

// SetPrevSameSource is a helper method to define mock.On call
//   - p Rule
func (_e *MockRule_Expecter) SetPrevSameSource(p any) *MockRule_SetPrevSameSource_Call {
	return &MockRule_SetPrevSameSource_Call{Call: _e.mock.On("SetPrevSameSource", p)}
}

func (_c *MockRule_SetPrevSameSource_Call) Run(run func(p Rule)) *MockRule_SetPrevSameSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Rule
		if args[0] != nil {
			arg0 = args[0].(Rule)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRule_SetPrevSameSource_Call) Return() *MockRule_SetPrevSameSource_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRule_SetPrevSameSource_Call) RunAndReturn(run func(p Rule)) *MockRule_SetPrevSameSource_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockRule
func (_mock *MockRule) Start(ctx context.Context) (<-chan struct{}, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 <-chan struct{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan struct{}, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan struct{}); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRule_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockRule_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRule_Expecter) Start(ctx any) *MockRule_Start_Call {
	return &MockRule_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockRule_Start_Call) Run(run func(ctx context.Context)) *MockRule_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRule_Start_Call) Return(valCh <-chan struct{}, err error) *MockRule_Start_Call {
	_c.Call.Return(valCh, err)
	return _c
}

func (_c *MockRule_Start_Call) RunAndReturn(run func(ctx context.Context) (<-chan struct{}, error)) *MockRule_Start_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRunnable creates a new instance of MockRunnable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunnable[I any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunnable[I] {
	mock := &MockRunnable[I]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunnable is an autogenerated mock type for the Runnable type
type MockRunnable[I any] struct {
	mock.Mock
}

type MockRunnable_Expecter[I any] struct {
	mock *mock.Mock
}

func (_m *MockRunnable[I]) EXPECT() *MockRunnable_Expecter[I] {
	return &MockRunnable_Expecter[I]{mock: &_m.Mock}
}

// NextRunnable provides a mock function for the type MockRunnable
func (_mock *MockRunnable[I]) NextRunnable() Runnable[I] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NextRunnable")
	}

	var r0 Runnable[I]
	if returnFunc, ok := ret.Get(0).(func() Runnable[I]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Runnable[I])
		}
	}
	return r0
}

// MockRunnable_NextRunnable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextRunnable'
type MockRunnable_NextRunnable_Call[I any] struct {
	*mock.Call
}

// NextRunnable is a helper method to define mock.On call
func (_e *MockRunnable_Expecter[I]) NextRunnable() *MockRunnable_NextRunnable_Call[I] {
	return &MockRunnable_NextRunnable_Call[I]{Call: _e.mock.On("NextRunnable")}
}

func (_c *MockRunnable_NextRunnable_Call[I]) Run(run func()) *MockRunnable_NextRunnable_Call[I] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRunnable_NextRunnable_Call[I]) Return(runnable Runnable[I]) *MockRunnable_NextRunnable_Call[I] {
	_c.Call.Return(runnable)
	return _c
}

func (_c *MockRunnable_NextRunnable_Call[I]) RunAndReturn(run func() Runnable[I]) *MockRunnable_NextRunnable_Call[I] {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockRunnable
func (_mock *MockRunnable[I]) Run(ctx context.Context, event I, syms boolexpr.Symbols) error {
	ret := _mock.Called(ctx, event, syms)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, I, boolexpr.Symbols) error); ok {
		r0 = returnFunc(ctx, event, syms)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRunnable_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRunnable_Run_Call[I any] struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - event I
//   - syms boolexpr.Symbols
func (_e *MockRunnable_Expecter[I]) Run(ctx any, event any, syms any) *MockRunnable_Run_Call[I] {
	return &MockRunnable_Run_Call[I]{Call: _e.mock.On("Run", ctx, event, syms)}
}

func (_c *MockRunnable_Run_Call[I]) Run(run func(ctx context.Context, event I, syms boolexpr.Symbols)) *MockRunnable_Run_Call[I] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 I
		if args[1] != nil {
			arg1 = args[1].(I)
		}
		var arg2 boolexpr.Symbols
		if args[2] != nil {
			arg2 = args[2].(boolexpr.Symbols)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRunnable_Run_Call[I]) Return(err error) *MockRunnable_Run_Call[I] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRunnable_Run_Call[I]) RunAndReturn(run func(ctx context.Context, event I, syms boolexpr.Symbols) error) *MockRunnable_Run_Call[I] {
	_c.Call.Return(run)
	return _c
}

// NewMockMiddleware creates a new instance of MockMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMiddleware[I any, O any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMiddleware[I, O] {
	mock := &MockMiddleware[I, O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMiddleware is an autogenerated mock type for the Middleware type
type MockMiddleware[I any, O any] struct {
	mock.Mock
}

type MockMiddleware_Expecter[I any, O any] struct {
	mock *mock.Mock
}

func (_m *MockMiddleware[I, O]) EXPECT() *MockMiddleware_Expecter[I, O] {
	return &MockMiddleware_Expecter[I, O]{mock: &_m.Mock}
}

// WrapAction provides a mock function for the type MockMiddleware
func (_mock *MockMiddleware[I, O]) WrapAction(ctx context.Context, rule Rule, action Action[I, O]) (Action[I, O], error) {
	ret := _mock.Called(ctx, rule, action)

	if len(ret) == 0 {
		panic("no return value specified for WrapAction")
	}

	var r0 Action[I, O]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Rule, Action[I, O]) (Action[I, O], error)); ok {
		return returnFunc(ctx, rule, action)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Rule, Action[I, O]) Action[I, O]); ok {
		r0 = returnFunc(ctx, rule, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Action[I, O])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Rule, Action[I, O]) error); ok {
		r1 = returnFunc(ctx, rule, action)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMiddleware_WrapAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WrapAction'
type MockMiddleware_WrapAction_Call[I any, O any] struct {
	*mock.Call
}

// WrapAction is a helper method to define mock.On call
//   - ctx context.Context
//   - rule Rule
//   - action Action[I, O]
func (_e *MockMiddleware_Expecter[I, O]) WrapAction(ctx any, rule any, action any) *MockMiddleware_WrapAction_Call[I, O] {
	return &MockMiddleware_WrapAction_Call[I, O]{Call: _e.mock.On("WrapAction", ctx, rule, action)}
}

func (_c *MockMiddleware_WrapAction_Call[I, O]) Run(run func(ctx context.Context, rule Rule, action Action[I, O])) *MockMiddleware_WrapAction_Call[I, O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Rule
		if args[1] != nil {
			arg1 = args[1].(Rule)
		}
		var arg2 Action[I, O]
		if args[2] != nil {
			arg2 = args[2].(Action[I, O])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMiddleware_WrapAction_Call[I, O]) Return(action1 Action[I, O], err error) *MockMiddleware_WrapAction_Call[I, O] {
	_c.Call.Return(action1, err)
	return _c
}

func (_c *MockMiddleware_WrapAction_Call[I, O]) RunAndReturn(run func(ctx context.Context, rule Rule, action Action[I, O]) (Action[I, O], error)) *MockMiddleware_WrapAction_Call[I, O] {
	_c.Call.Return(run)
	return _c
}

// WrapCallback provides a mock function for the type MockMiddleware
func (_mock *MockMiddleware[I, O]) WrapCallback(ctx context.Context, rule Rule, callback Callback[I]) (Callback[I], error) {
	ret := _mock.Called(ctx, rule, callback)

	if len(ret) == 0 {
		panic("no return value specified for WrapCallback")
	}

	var r0 Callback[I]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Rule, Callback[I]) (Callback[I], error)); ok {
		return returnFunc(ctx, rule, callback)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Rule, Callback[I]) Callback[I]); ok {
		r0 = returnFunc(ctx, rule, callback)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Callback[I])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Rule, Callback[I]) error); ok {
		r1 = returnFunc(ctx, rule, callback)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMiddleware_WrapCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WrapCallback'
type MockMiddleware_WrapCallback_Call[I any, O any] struct {
	*mock.Call
}

// WrapCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - rule Rule
//   - callback Callback[I]
func (_e *MockMiddleware_Expecter[I, O]) WrapCallback(ctx any, rule any, callback any) *MockMiddleware_WrapCallback_Call[I, O] {
	return &MockMiddleware_WrapCallback_Call[I, O]{Call: _e.mock.On("WrapCallback", ctx, rule, callback)}
}

func (_c *MockMiddleware_WrapCallback_Call[I, O]) Run(run func(ctx context.Context, rule Rule, callback Callback[I])) *MockMiddleware_WrapCallback_Call[I, O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Rule
		if args[1] != nil {
			arg1 = args[1].(Rule)
		}
		var arg2 Callback[I]
		if args[2] != nil {
			arg2 = args[2].(Callback[I])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMiddleware_WrapCallback_Call[I, O]) Return(callback1 Callback[I], err error) *MockMiddleware_WrapCallback_Call[I, O] {
	_c.Call.Return(callback1, err)
	return _c
}

func (_c *MockMiddleware_WrapCallback_Call[I, O]) RunAndReturn(run func(ctx context.Context, rule Rule, callback Callback[I]) (Callback[I], error)) *MockMiddleware_WrapCallback_Call[I, O] {
	_c.Call.Return(run)
	return _c
}

// WrapDestination provides a mock function for the type MockMiddleware
func (_mock *MockMiddleware[I, O]) WrapDestination(ctx context.Context, rule Rule, destination Destination[O]) (Destination[O], error) {
	ret := _mock.Called(ctx, rule, destination)

	if len(ret) == 0 {
		panic("no return value specified for WrapDestination")
	}

	var r0 Destination[O]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Rule, Destination[O]) (Destination[O], error)); ok {
		return returnFunc(ctx, rule, destination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Rule, Destination[O]) Destination[O]); ok {
		r0 = returnFunc(ctx, rule, destination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Destination[O])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Rule, Destination[O]) error); ok {
		r1 = returnFunc(ctx, rule, destination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMiddleware_WrapDestination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WrapDestination'
type MockMiddleware_WrapDestination_Call[I any, O any] struct {
	*mock.Call
}

// WrapDestination is a helper method to define mock.On call
//   - ctx context.Context
//   - rule Rule
//   - destination Destination[O]
func (_e *MockMiddleware_Expecter[I, O]) WrapDestination(ctx any, rule any, destination any) *MockMiddleware_WrapDestination_Call[I, O] {
	return &MockMiddleware_WrapDestination_Call[I, O]{Call: _e.mock.On("WrapDestination", ctx, rule, destination)}
}

func (_c *MockMiddleware_WrapDestination_Call[I, O]) Run(run func(ctx context.Context, rule Rule, destination Destination[O])) *MockMiddleware_WrapDestination_Call[I, O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Rule
		if args[1] != nil {
			arg1 = args[1].(Rule)
		}
		var arg2 Destination[O]
		if args[2] != nil {
			arg2 = args[2].(Destination[O])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMiddleware_WrapDestination_Call[I, O]) Return(destination1 Destination[O], err error) *MockMiddleware_WrapDestination_Call[I, O] {
	_c.Call.Return(destination1, err)
	return _c
}

func (_c *MockMiddleware_WrapDestination_Call[I, O]) RunAndReturn(run func(ctx context.Context, rule Rule, destination Destination[O]) (Destination[O], error)) *MockMiddleware_WrapDestination_Call[I, O] {
	_c.Call.Return(run)
	return _c
}
