// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package firehose

import (
	"context"

	"github.com/emad-elsaid/boolexpr"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEvent creates a new instance of MockEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvent {
	mock := &MockEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvent is an autogenerated mock type for the Event type
type MockEvent struct {
	mock.Mock
}

type MockEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvent) EXPECT() *MockEvent_Expecter {
	return &MockEvent_Expecter{mock: &_m.Mock}
}

// NewMockAttributer creates a new instance of MockAttributer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAttributer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAttributer {
	mock := &MockAttributer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAttributer is an autogenerated mock type for the Attributer type
type MockAttributer struct {
	mock.Mock
}

type MockAttributer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAttributer) EXPECT() *MockAttributer_Expecter {
	return &MockAttributer_Expecter{mock: &_m.Mock}
}

// Attributes provides a mock function for the type MockAttributer
func (_mock *MockAttributer) Attributes(ctx context.Context) (map[string]any, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Attributes")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[string]any, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[string]any); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAttributer_Attributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attributes'
type MockAttributer_Attributes_Call struct {
	*mock.Call
}

// Attributes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAttributer_Expecter) Attributes(ctx any) *MockAttributer_Attributes_Call {
	return &MockAttributer_Attributes_Call{Call: _e.mock.On("Attributes", ctx)}
}

func (_c *MockAttributer_Attributes_Call) Run(run func(ctx context.Context)) *MockAttributer_Attributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAttributer_Attributes_Call) Return(stringToV map[string]any, err error) *MockAttributer_Attributes_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockAttributer_Attributes_Call) RunAndReturn(run func(ctx context.Context) (map[string]any, error)) *MockAttributer_Attributes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource[T] {
	mock := &MockSource[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource[T any] struct {
	mock.Mock
}

type MockSource_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockSource[T]) EXPECT() *MockSource_Expecter[T] {
	return &MockSource_Expecter[T]{mock: &_m.Mock}
}

// Start provides a mock function for the type MockSource
func (_mock *MockSource[T]) Start(ctx context.Context, cb Callback[T]) (context.Context, error) {
	ret := _mock.Called(ctx, cb)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 context.Context
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Callback[T]) (context.Context, error)); ok {
		return returnFunc(ctx, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Callback[T]) context.Context); ok {
		r0 = returnFunc(ctx, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Callback[T]) error); ok {
		r1 = returnFunc(ctx, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSource_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockSource_Start_Call[T any] struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - cb Callback[T]
func (_e *MockSource_Expecter[T]) Start(ctx any, cb any) *MockSource_Start_Call[T] {
	return &MockSource_Start_Call[T]{Call: _e.mock.On("Start", ctx, cb)}
}

func (_c *MockSource_Start_Call[T]) Run(run func(ctx context.Context, cb Callback[T])) *MockSource_Start_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Callback[T]
		if args[1] != nil {
			arg1 = args[1].(Callback[T])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSource_Start_Call[T]) Return(done context.Context, err error) *MockSource_Start_Call[T] {
	_c.Call.Return(done, err)
	return _c
}

func (_c *MockSource_Start_Call[T]) RunAndReturn(run func(ctx context.Context, cb Callback[T]) (context.Context, error)) *MockSource_Start_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockAction creates a new instance of MockAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAction[I any, O any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAction[I, O] {
	mock := &MockAction[I, O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAction is an autogenerated mock type for the Action type
type MockAction[I any, O any] struct {
	mock.Mock
}

type MockAction_Expecter[I any, O any] struct {
	mock *mock.Mock
}

func (_m *MockAction[I, O]) EXPECT() *MockAction_Expecter[I, O] {
	return &MockAction_Expecter[I, O]{mock: &_m.Mock}
}

// Process provides a mock function for the type MockAction
func (_mock *MockAction[I, O]) Process(ctx context.Context, event I, syms boolexpr.Symbols) (O, Report) {
	ret := _mock.Called(ctx, event, syms)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 O
	var r1 Report
	if returnFunc, ok := ret.Get(0).(func(context.Context, I, boolexpr.Symbols) (O, Report)); ok {
		return returnFunc(ctx, event, syms)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, I, boolexpr.Symbols) O); ok {
		r0 = returnFunc(ctx, event, syms)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(O)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, I, boolexpr.Symbols) Report); ok {
		r1 = returnFunc(ctx, event, syms)
	} else {
		r1 = ret.Get(1).(Report)
	}
	return r0, r1
}

// MockAction_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockAction_Process_Call[I any, O any] struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - event I
//   - syms boolexpr.Symbols
func (_e *MockAction_Expecter[I, O]) Process(ctx any, event any, syms any) *MockAction_Process_Call[I, O] {
	return &MockAction_Process_Call[I, O]{Call: _e.mock.On("Process", ctx, event, syms)}
}

func (_c *MockAction_Process_Call[I, O]) Run(run func(ctx context.Context, event I, syms boolexpr.Symbols)) *MockAction_Process_Call[I, O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 I
		if args[1] != nil {
			arg1 = args[1].(I)
		}
		var arg2 boolexpr.Symbols
		if args[2] != nil {
			arg2 = args[2].(boolexpr.Symbols)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAction_Process_Call[I, O]) Return(v O, report Report) *MockAction_Process_Call[I, O] {
	_c.Call.Return(v, report)
	return _c
}

func (_c *MockAction_Process_Call[I, O]) RunAndReturn(run func(ctx context.Context, event I, syms boolexpr.Symbols) (O, Report)) *MockAction_Process_Call[I, O] {
	_c.Call.Return(run)
	return _c
}

// NewMockDestination creates a new instance of MockDestination. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDestination[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDestination[T] {
	mock := &MockDestination[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDestination is an autogenerated mock type for the Destination type
type MockDestination[T any] struct {
	mock.Mock
}

type MockDestination_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockDestination[T]) EXPECT() *MockDestination_Expecter[T] {
	return &MockDestination_Expecter[T]{mock: &_m.Mock}
}

// Send provides a mock function for the type MockDestination
func (_mock *MockDestination[T]) Send(ctx context.Context, event T) Report {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 Report
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) Report); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Get(0).(Report)
	}
	return r0
}

// MockDestination_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockDestination_Send_Call[T any] struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - event T
func (_e *MockDestination_Expecter[T]) Send(ctx any, event any) *MockDestination_Send_Call[T] {
	return &MockDestination_Send_Call[T]{Call: _e.mock.On("Send", ctx, event)}
}

func (_c *MockDestination_Send_Call[T]) Run(run func(ctx context.Context, event T)) *MockDestination_Send_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDestination_Send_Call[T]) Return(report Report) *MockDestination_Send_Call[T] {
	_c.Call.Return(report)
	return _c
}

func (_c *MockDestination_Send_Call[T]) RunAndReturn(run func(ctx context.Context, event T) Report) *MockDestination_Send_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// getCtx provides a mock function for the type MockRegistry
func (_mock *MockRegistry) getCtx() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getCtx")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockRegistry_getCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getCtx'
type MockRegistry_getCtx_Call struct {
	*mock.Call
}

// getCtx is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) getCtx() *MockRegistry_getCtx_Call {
	return &MockRegistry_getCtx_Call{Call: _e.mock.On("getCtx")}
}

func (_c *MockRegistry_getCtx_Call) Run(run func()) *MockRegistry_getCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_getCtx_Call) Return(context1 context.Context) *MockRegistry_getCtx_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockRegistry_getCtx_Call) RunAndReturn(run func() context.Context) *MockRegistry_getCtx_Call {
	_c.Call.Return(run)
	return _c
}

// getNext provides a mock function for the type MockRegistry
func (_mock *MockRegistry) getNext() Registry {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getNext")
	}

	var r0 Registry
	if returnFunc, ok := ret.Get(0).(func() Registry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Registry)
		}
	}
	return r0
}

// MockRegistry_getNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getNext'
type MockRegistry_getNext_Call struct {
	*mock.Call
}

// getNext is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) getNext() *MockRegistry_getNext_Call {
	return &MockRegistry_getNext_Call{Call: _e.mock.On("getNext")}
}

func (_c *MockRegistry_getNext_Call) Run(run func()) *MockRegistry_getNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_getNext_Call) Return(registry Registry) *MockRegistry_getNext_Call {
	_c.Call.Return(registry)
	return _c
}

func (_c *MockRegistry_getNext_Call) RunAndReturn(run func() Registry) *MockRegistry_getNext_Call {
	_c.Call.Return(run)
	return _c
}

// getPrev provides a mock function for the type MockRegistry
func (_mock *MockRegistry) getPrev() Registry {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getPrev")
	}

	var r0 Registry
	if returnFunc, ok := ret.Get(0).(func() Registry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Registry)
		}
	}
	return r0
}

// MockRegistry_getPrev_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getPrev'
type MockRegistry_getPrev_Call struct {
	*mock.Call
}

// getPrev is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) getPrev() *MockRegistry_getPrev_Call {
	return &MockRegistry_getPrev_Call{Call: _e.mock.On("getPrev")}
}

func (_c *MockRegistry_getPrev_Call) Run(run func()) *MockRegistry_getPrev_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_getPrev_Call) Return(registry Registry) *MockRegistry_getPrev_Call {
	_c.Call.Return(registry)
	return _c
}

func (_c *MockRegistry_getPrev_Call) RunAndReturn(run func() Registry) *MockRegistry_getPrev_Call {
	_c.Call.Return(run)
	return _c
}

// getSource provides a mock function for the type MockRegistry
func (_mock *MockRegistry) getSource() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getSource")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockRegistry_getSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getSource'
type MockRegistry_getSource_Call struct {
	*mock.Call
}

// getSource is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) getSource() *MockRegistry_getSource_Call {
	return &MockRegistry_getSource_Call{Call: _e.mock.On("getSource")}
}

func (_c *MockRegistry_getSource_Call) Run(run func()) *MockRegistry_getSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_getSource_Call) Return(v any) *MockRegistry_getSource_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockRegistry_getSource_Call) RunAndReturn(run func() any) *MockRegistry_getSource_Call {
	_c.Call.Return(run)
	return _c
}

// getSourceRegistry provides a mock function for the type MockRegistry
func (_mock *MockRegistry) getSourceRegistry() sourceRegistry {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getSourceRegistry")
	}

	var r0 sourceRegistry
	if returnFunc, ok := ret.Get(0).(func() sourceRegistry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sourceRegistry)
		}
	}
	return r0
}

// MockRegistry_getSourceRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getSourceRegistry'
type MockRegistry_getSourceRegistry_Call struct {
	*mock.Call
}

// getSourceRegistry is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) getSourceRegistry() *MockRegistry_getSourceRegistry_Call {
	return &MockRegistry_getSourceRegistry_Call{Call: _e.mock.On("getSourceRegistry")}
}

func (_c *MockRegistry_getSourceRegistry_Call) Run(run func()) *MockRegistry_getSourceRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_getSourceRegistry_Call) Return(sourceRegistryMoqParam sourceRegistry) *MockRegistry_getSourceRegistry_Call {
	_c.Call.Return(sourceRegistryMoqParam)
	return _c
}

func (_c *MockRegistry_getSourceRegistry_Call) RunAndReturn(run func() sourceRegistry) *MockRegistry_getSourceRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// setNext provides a mock function for the type MockRegistry
func (_mock *MockRegistry) setNext(n Registry) {
	_mock.Called(n)
	return
}

// MockRegistry_setNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setNext'
type MockRegistry_setNext_Call struct {
	*mock.Call
}

// setNext is a helper method to define mock.On call
//   - n Registry
func (_e *MockRegistry_Expecter) setNext(n any) *MockRegistry_setNext_Call {
	return &MockRegistry_setNext_Call{Call: _e.mock.On("setNext", n)}
}

func (_c *MockRegistry_setNext_Call) Run(run func(n Registry)) *MockRegistry_setNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Registry
		if args[0] != nil {
			arg0 = args[0].(Registry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_setNext_Call) Return() *MockRegistry_setNext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistry_setNext_Call) RunAndReturn(run func(n Registry)) *MockRegistry_setNext_Call {
	_c.Run(run)
	return _c
}

// setPrev provides a mock function for the type MockRegistry
func (_mock *MockRegistry) setPrev(p Registry) {
	_mock.Called(p)
	return
}

// MockRegistry_setPrev_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setPrev'
type MockRegistry_setPrev_Call struct {
	*mock.Call
}

// setPrev is a helper method to define mock.On call
//   - p Registry
func (_e *MockRegistry_Expecter) setPrev(p any) *MockRegistry_setPrev_Call {
	return &MockRegistry_setPrev_Call{Call: _e.mock.On("setPrev", p)}
}

func (_c *MockRegistry_setPrev_Call) Run(run func(p Registry)) *MockRegistry_setPrev_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Registry
		if args[0] != nil {
			arg0 = args[0].(Registry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_setPrev_Call) Return() *MockRegistry_setPrev_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistry_setPrev_Call) RunAndReturn(run func(p Registry)) *MockRegistry_setPrev_Call {
	_c.Run(run)
	return _c
}

// start provides a mock function for the type MockRegistry
func (_mock *MockRegistry) start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistry_start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'start'
type MockRegistry_start_Call struct {
	*mock.Call
}

// start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRegistry_Expecter) start(ctx any) *MockRegistry_start_Call {
	return &MockRegistry_start_Call{Call: _e.mock.On("start", ctx)}
}

func (_c *MockRegistry_start_Call) Run(run func(ctx context.Context)) *MockRegistry_start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistry_start_Call) Return(err error) *MockRegistry_start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistry_start_Call) RunAndReturn(run func(ctx context.Context) error) *MockRegistry_start_Call {
	_c.Call.Return(run)
	return _c
}

// newMocksourceRegistry creates a new instance of mocksourceRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksourceRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksourceRegistry {
	mock := &mocksourceRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocksourceRegistry is an autogenerated mock type for the sourceRegistry type
type mocksourceRegistry struct {
	mock.Mock
}

type mocksourceRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksourceRegistry) EXPECT() *mocksourceRegistry_Expecter {
	return &mocksourceRegistry_Expecter{mock: &_m.Mock}
}

// getNextSameSource provides a mock function for the type mocksourceRegistry
func (_mock *mocksourceRegistry) getNextSameSource() sourceRegistry {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getNextSameSource")
	}

	var r0 sourceRegistry
	if returnFunc, ok := ret.Get(0).(func() sourceRegistry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sourceRegistry)
		}
	}
	return r0
}

// mocksourceRegistry_getNextSameSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getNextSameSource'
type mocksourceRegistry_getNextSameSource_Call struct {
	*mock.Call
}

// getNextSameSource is a helper method to define mock.On call
func (_e *mocksourceRegistry_Expecter) getNextSameSource() *mocksourceRegistry_getNextSameSource_Call {
	return &mocksourceRegistry_getNextSameSource_Call{Call: _e.mock.On("getNextSameSource")}
}

func (_c *mocksourceRegistry_getNextSameSource_Call) Run(run func()) *mocksourceRegistry_getNextSameSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocksourceRegistry_getNextSameSource_Call) Return(sourceRegistryMoqParam sourceRegistry) *mocksourceRegistry_getNextSameSource_Call {
	_c.Call.Return(sourceRegistryMoqParam)
	return _c
}

func (_c *mocksourceRegistry_getNextSameSource_Call) RunAndReturn(run func() sourceRegistry) *mocksourceRegistry_getNextSameSource_Call {
	_c.Call.Return(run)
	return _c
}

// getRegistry provides a mock function for the type mocksourceRegistry
func (_mock *mocksourceRegistry) getRegistry() Registry {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getRegistry")
	}

	var r0 Registry
	if returnFunc, ok := ret.Get(0).(func() Registry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Registry)
		}
	}
	return r0
}

// mocksourceRegistry_getRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getRegistry'
type mocksourceRegistry_getRegistry_Call struct {
	*mock.Call
}

// getRegistry is a helper method to define mock.On call
func (_e *mocksourceRegistry_Expecter) getRegistry() *mocksourceRegistry_getRegistry_Call {
	return &mocksourceRegistry_getRegistry_Call{Call: _e.mock.On("getRegistry")}
}

func (_c *mocksourceRegistry_getRegistry_Call) Run(run func()) *mocksourceRegistry_getRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mocksourceRegistry_getRegistry_Call) Return(registry Registry) *mocksourceRegistry_getRegistry_Call {
	_c.Call.Return(registry)
	return _c
}

func (_c *mocksourceRegistry_getRegistry_Call) RunAndReturn(run func() Registry) *mocksourceRegistry_getRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// setNextSameSource provides a mock function for the type mocksourceRegistry
func (_mock *mocksourceRegistry) setNextSameSource(n sourceRegistry) {
	_mock.Called(n)
	return
}

// mocksourceRegistry_setNextSameSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setNextSameSource'
type mocksourceRegistry_setNextSameSource_Call struct {
	*mock.Call
}

// setNextSameSource is a helper method to define mock.On call
//   - n sourceRegistry
func (_e *mocksourceRegistry_Expecter) setNextSameSource(n any) *mocksourceRegistry_setNextSameSource_Call {
	return &mocksourceRegistry_setNextSameSource_Call{Call: _e.mock.On("setNextSameSource", n)}
}

func (_c *mocksourceRegistry_setNextSameSource_Call) Run(run func(n sourceRegistry)) *mocksourceRegistry_setNextSameSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sourceRegistry
		if args[0] != nil {
			arg0 = args[0].(sourceRegistry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocksourceRegistry_setNextSameSource_Call) Return() *mocksourceRegistry_setNextSameSource_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocksourceRegistry_setNextSameSource_Call) RunAndReturn(run func(n sourceRegistry)) *mocksourceRegistry_setNextSameSource_Call {
	_c.Run(run)
	return _c
}

// setPrevSameSource provides a mock function for the type mocksourceRegistry
func (_mock *mocksourceRegistry) setPrevSameSource(p sourceRegistry) {
	_mock.Called(p)
	return
}

// mocksourceRegistry_setPrevSameSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setPrevSameSource'
type mocksourceRegistry_setPrevSameSource_Call struct {
	*mock.Call
}

// setPrevSameSource is a helper method to define mock.On call
//   - p sourceRegistry
func (_e *mocksourceRegistry_Expecter) setPrevSameSource(p any) *mocksourceRegistry_setPrevSameSource_Call {
	return &mocksourceRegistry_setPrevSameSource_Call{Call: _e.mock.On("setPrevSameSource", p)}
}

func (_c *mocksourceRegistry_setPrevSameSource_Call) Run(run func(p sourceRegistry)) *mocksourceRegistry_setPrevSameSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sourceRegistry
		if args[0] != nil {
			arg0 = args[0].(sourceRegistry)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocksourceRegistry_setPrevSameSource_Call) Return() *mocksourceRegistry_setPrevSameSource_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocksourceRegistry_setPrevSameSource_Call) RunAndReturn(run func(p sourceRegistry)) *mocksourceRegistry_setPrevSameSource_Call {
	_c.Run(run)
	return _c
}

// NewMockRunnable creates a new instance of MockRunnable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunnable[I any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunnable[I] {
	mock := &MockRunnable[I]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunnable is an autogenerated mock type for the Runnable type
type MockRunnable[I any] struct {
	mock.Mock
}

type MockRunnable_Expecter[I any] struct {
	mock *mock.Mock
}

func (_m *MockRunnable[I]) EXPECT() *MockRunnable_Expecter[I] {
	return &MockRunnable_Expecter[I]{mock: &_m.Mock}
}

// NextRunnable provides a mock function for the type MockRunnable
func (_mock *MockRunnable[I]) NextRunnable() Runnable[I] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NextRunnable")
	}

	var r0 Runnable[I]
	if returnFunc, ok := ret.Get(0).(func() Runnable[I]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Runnable[I])
		}
	}
	return r0
}

// MockRunnable_NextRunnable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextRunnable'
type MockRunnable_NextRunnable_Call[I any] struct {
	*mock.Call
}

// NextRunnable is a helper method to define mock.On call
func (_e *MockRunnable_Expecter[I]) NextRunnable() *MockRunnable_NextRunnable_Call[I] {
	return &MockRunnable_NextRunnable_Call[I]{Call: _e.mock.On("NextRunnable")}
}

func (_c *MockRunnable_NextRunnable_Call[I]) Run(run func()) *MockRunnable_NextRunnable_Call[I] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRunnable_NextRunnable_Call[I]) Return(runnable Runnable[I]) *MockRunnable_NextRunnable_Call[I] {
	_c.Call.Return(runnable)
	return _c
}

func (_c *MockRunnable_NextRunnable_Call[I]) RunAndReturn(run func() Runnable[I]) *MockRunnable_NextRunnable_Call[I] {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockRunnable
func (_mock *MockRunnable[I]) Run(ctx context.Context, event I, syms boolexpr.Symbols, reports chan<- Report) {
	_mock.Called(ctx, event, syms, reports)
	return
}

// MockRunnable_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRunnable_Run_Call[I any] struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - event I
//   - syms boolexpr.Symbols
//   - reports chan<- Report
func (_e *MockRunnable_Expecter[I]) Run(ctx any, event any, syms any, reports any) *MockRunnable_Run_Call[I] {
	return &MockRunnable_Run_Call[I]{Call: _e.mock.On("Run", ctx, event, syms, reports)}
}

func (_c *MockRunnable_Run_Call[I]) Run(run func(ctx context.Context, event I, syms boolexpr.Symbols, reports chan<- Report)) *MockRunnable_Run_Call[I] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 I
		if args[1] != nil {
			arg1 = args[1].(I)
		}
		var arg2 boolexpr.Symbols
		if args[2] != nil {
			arg2 = args[2].(boolexpr.Symbols)
		}
		var arg3 chan<- Report
		if args[3] != nil {
			arg3 = args[3].(chan<- Report)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRunnable_Run_Call[I]) Return() *MockRunnable_Run_Call[I] {
	_c.Call.Return()
	return _c
}

func (_c *MockRunnable_Run_Call[I]) RunAndReturn(run func(ctx context.Context, event I, syms boolexpr.Symbols, reports chan<- Report)) *MockRunnable_Run_Call[I] {
	_c.Run(run)
	return _c
}

// NewMockActionMiddleware creates a new instance of MockActionMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActionMiddleware[I Event, O Event](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActionMiddleware[I, O] {
	mock := &MockActionMiddleware[I, O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActionMiddleware is an autogenerated mock type for the ActionMiddleware type
type MockActionMiddleware[I Event, O Event] struct {
	mock.Mock
}

type MockActionMiddleware_Expecter[I Event, O Event] struct {
	mock *mock.Mock
}

func (_m *MockActionMiddleware[I, O]) EXPECT() *MockActionMiddleware_Expecter[I, O] {
	return &MockActionMiddleware_Expecter[I, O]{mock: &_m.Mock}
}

// Wrap provides a mock function for the type MockActionMiddleware
func (_mock *MockActionMiddleware[I, O]) Wrap(ctx context.Context, rule Rule[I, O], action Action[I, O], in I) (Action[I, O], error) {
	ret := _mock.Called(ctx, rule, action, in)

	if len(ret) == 0 {
		panic("no return value specified for Wrap")
	}

	var r0 Action[I, O]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Rule[I, O], Action[I, O], I) (Action[I, O], error)); ok {
		return returnFunc(ctx, rule, action, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Rule[I, O], Action[I, O], I) Action[I, O]); ok {
		r0 = returnFunc(ctx, rule, action, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Action[I, O])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Rule[I, O], Action[I, O], I) error); ok {
		r1 = returnFunc(ctx, rule, action, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActionMiddleware_Wrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wrap'
type MockActionMiddleware_Wrap_Call[I Event, O Event] struct {
	*mock.Call
}

// Wrap is a helper method to define mock.On call
//   - ctx context.Context
//   - rule Rule[I, O]
//   - action Action[I, O]
//   - in I
func (_e *MockActionMiddleware_Expecter[I, O]) Wrap(ctx any, rule any, action any, in any) *MockActionMiddleware_Wrap_Call[I, O] {
	return &MockActionMiddleware_Wrap_Call[I, O]{Call: _e.mock.On("Wrap", ctx, rule, action, in)}
}

func (_c *MockActionMiddleware_Wrap_Call[I, O]) Run(run func(ctx context.Context, rule Rule[I, O], action Action[I, O], in I)) *MockActionMiddleware_Wrap_Call[I, O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Rule[I, O]
		if args[1] != nil {
			arg1 = args[1].(Rule[I, O])
		}
		var arg2 Action[I, O]
		if args[2] != nil {
			arg2 = args[2].(Action[I, O])
		}
		var arg3 I
		if args[3] != nil {
			arg3 = args[3].(I)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockActionMiddleware_Wrap_Call[I, O]) Return(action1 Action[I, O], err error) *MockActionMiddleware_Wrap_Call[I, O] {
	_c.Call.Return(action1, err)
	return _c
}

func (_c *MockActionMiddleware_Wrap_Call[I, O]) RunAndReturn(run func(ctx context.Context, rule Rule[I, O], action Action[I, O], in I) (Action[I, O], error)) *MockActionMiddleware_Wrap_Call[I, O] {
	_c.Call.Return(run)
	return _c
}

// NewMockDestinationMiddleware creates a new instance of MockDestinationMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDestinationMiddleware[I Event, O Event](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDestinationMiddleware[I, O] {
	mock := &MockDestinationMiddleware[I, O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDestinationMiddleware is an autogenerated mock type for the DestinationMiddleware type
type MockDestinationMiddleware[I Event, O Event] struct {
	mock.Mock
}

type MockDestinationMiddleware_Expecter[I Event, O Event] struct {
	mock *mock.Mock
}

func (_m *MockDestinationMiddleware[I, O]) EXPECT() *MockDestinationMiddleware_Expecter[I, O] {
	return &MockDestinationMiddleware_Expecter[I, O]{mock: &_m.Mock}
}

// Wrap provides a mock function for the type MockDestinationMiddleware
func (_mock *MockDestinationMiddleware[I, O]) Wrap(ctx context.Context, rule Rule[I, O], destination Destination[O], out O) (Destination[O], error) {
	ret := _mock.Called(ctx, rule, destination, out)

	if len(ret) == 0 {
		panic("no return value specified for Wrap")
	}

	var r0 Destination[O]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Rule[I, O], Destination[O], O) (Destination[O], error)); ok {
		return returnFunc(ctx, rule, destination, out)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, Rule[I, O], Destination[O], O) Destination[O]); ok {
		r0 = returnFunc(ctx, rule, destination, out)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Destination[O])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, Rule[I, O], Destination[O], O) error); ok {
		r1 = returnFunc(ctx, rule, destination, out)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDestinationMiddleware_Wrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wrap'
type MockDestinationMiddleware_Wrap_Call[I Event, O Event] struct {
	*mock.Call
}

// Wrap is a helper method to define mock.On call
//   - ctx context.Context
//   - rule Rule[I, O]
//   - destination Destination[O]
//   - out O
func (_e *MockDestinationMiddleware_Expecter[I, O]) Wrap(ctx any, rule any, destination any, out any) *MockDestinationMiddleware_Wrap_Call[I, O] {
	return &MockDestinationMiddleware_Wrap_Call[I, O]{Call: _e.mock.On("Wrap", ctx, rule, destination, out)}
}

func (_c *MockDestinationMiddleware_Wrap_Call[I, O]) Run(run func(ctx context.Context, rule Rule[I, O], destination Destination[O], out O)) *MockDestinationMiddleware_Wrap_Call[I, O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Rule[I, O]
		if args[1] != nil {
			arg1 = args[1].(Rule[I, O])
		}
		var arg2 Destination[O]
		if args[2] != nil {
			arg2 = args[2].(Destination[O])
		}
		var arg3 O
		if args[3] != nil {
			arg3 = args[3].(O)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDestinationMiddleware_Wrap_Call[I, O]) Return(destination1 Destination[O], err error) *MockDestinationMiddleware_Wrap_Call[I, O] {
	_c.Call.Return(destination1, err)
	return _c
}

func (_c *MockDestinationMiddleware_Wrap_Call[I, O]) RunAndReturn(run func(ctx context.Context, rule Rule[I, O], destination Destination[O], out O) (Destination[O], error)) *MockDestinationMiddleware_Wrap_Call[I, O] {
	_c.Call.Return(run)
	return _c
}

// NewMockCallbackMiddleware creates a new instance of MockCallbackMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCallbackMiddleware[I Event, O Event](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCallbackMiddleware[I, O] {
	mock := &MockCallbackMiddleware[I, O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCallbackMiddleware is an autogenerated mock type for the CallbackMiddleware type
type MockCallbackMiddleware[I Event, O Event] struct {
	mock.Mock
}

type MockCallbackMiddleware_Expecter[I Event, O Event] struct {
	mock *mock.Mock
}

func (_m *MockCallbackMiddleware[I, O]) EXPECT() *MockCallbackMiddleware_Expecter[I, O] {
	return &MockCallbackMiddleware_Expecter[I, O]{mock: &_m.Mock}
}

// Wrap provides a mock function for the type MockCallbackMiddleware
func (_mock *MockCallbackMiddleware[I, O]) Wrap(ctx context.Context, rule *Rule[I, O], callback Callback[I], in I) (Callback[I], error) {
	ret := _mock.Called(ctx, rule, callback, in)

	if len(ret) == 0 {
		panic("no return value specified for Wrap")
	}

	var r0 Callback[I]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Rule[I, O], Callback[I], I) (Callback[I], error)); ok {
		return returnFunc(ctx, rule, callback, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Rule[I, O], Callback[I], I) Callback[I]); ok {
		r0 = returnFunc(ctx, rule, callback, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Callback[I])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *Rule[I, O], Callback[I], I) error); ok {
		r1 = returnFunc(ctx, rule, callback, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCallbackMiddleware_Wrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wrap'
type MockCallbackMiddleware_Wrap_Call[I Event, O Event] struct {
	*mock.Call
}

// Wrap is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *Rule[I, O]
//   - callback Callback[I]
//   - in I
func (_e *MockCallbackMiddleware_Expecter[I, O]) Wrap(ctx any, rule any, callback any, in any) *MockCallbackMiddleware_Wrap_Call[I, O] {
	return &MockCallbackMiddleware_Wrap_Call[I, O]{Call: _e.mock.On("Wrap", ctx, rule, callback, in)}
}

func (_c *MockCallbackMiddleware_Wrap_Call[I, O]) Run(run func(ctx context.Context, rule *Rule[I, O], callback Callback[I], in I)) *MockCallbackMiddleware_Wrap_Call[I, O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Rule[I, O]
		if args[1] != nil {
			arg1 = args[1].(*Rule[I, O])
		}
		var arg2 Callback[I]
		if args[2] != nil {
			arg2 = args[2].(Callback[I])
		}
		var arg3 I
		if args[3] != nil {
			arg3 = args[3].(I)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCallbackMiddleware_Wrap_Call[I, O]) Return(callback1 Callback[I], err error) *MockCallbackMiddleware_Wrap_Call[I, O] {
	_c.Call.Return(callback1, err)
	return _c
}

func (_c *MockCallbackMiddleware_Wrap_Call[I, O]) RunAndReturn(run func(ctx context.Context, rule *Rule[I, O], callback Callback[I], in I) (Callback[I], error)) *MockCallbackMiddleware_Wrap_Call[I, O] {
	_c.Call.Return(run)
	return _c
}
