// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ifs

import (
	"context"
	"time"

	"github.com/emad-elsaid/firehose"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheStorage creates a new instance of MockCacheStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheStorage[V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheStorage[V] {
	mock := &MockCacheStorage[V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheStorage is an autogenerated mock type for the CacheStorage type
type MockCacheStorage[V any] struct {
	mock.Mock
}

type MockCacheStorage_Expecter[V any] struct {
	mock *mock.Mock
}

func (_m *MockCacheStorage[V]) EXPECT() *MockCacheStorage_Expecter[V] {
	return &MockCacheStorage_Expecter[V]{mock: &_m.Mock}
}

// Get provides a mock function for the type MockCacheStorage
func (_mock *MockCacheStorage[V]) Get(ctx context.Context, key string) (V, firehose.Report, bool) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 V
	var r1 firehose.Report
	var r2 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (V, firehose.Report, bool)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) V); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) firehose.Report); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Get(1).(firehose.Report)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) bool); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Get(2).(bool)
	}
	return r0, r1, r2
}

// MockCacheStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheStorage_Get_Call[V any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheStorage_Expecter[V]) Get(ctx any, key any) *MockCacheStorage_Get_Call[V] {
	return &MockCacheStorage_Get_Call[V]{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockCacheStorage_Get_Call[V]) Run(run func(ctx context.Context, key string)) *MockCacheStorage_Get_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheStorage_Get_Call[V]) Return(value V, report firehose.Report, ok bool) *MockCacheStorage_Get_Call[V] {
	_c.Call.Return(value, report, ok)
	return _c
}

func (_c *MockCacheStorage_Get_Call[V]) RunAndReturn(run func(ctx context.Context, key string) (V, firehose.Report, bool)) *MockCacheStorage_Get_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCacheStorage
func (_mock *MockCacheStorage[V]) Set(ctx context.Context, key string, value V, report firehose.Report, ttl time.Duration) firehose.Report {
	ret := _mock.Called(ctx, key, value, report, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 firehose.Report
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, V, firehose.Report, time.Duration) firehose.Report); ok {
		r0 = returnFunc(ctx, key, value, report, ttl)
	} else {
		r0 = ret.Get(0).(firehose.Report)
	}
	return r0
}

// MockCacheStorage_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCacheStorage_Set_Call[V any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value V
//   - report firehose.Report
//   - ttl time.Duration
func (_e *MockCacheStorage_Expecter[V]) Set(ctx any, key any, value any, report any, ttl any) *MockCacheStorage_Set_Call[V] {
	return &MockCacheStorage_Set_Call[V]{Call: _e.mock.On("Set", ctx, key, value, report, ttl)}
}

func (_c *MockCacheStorage_Set_Call[V]) Run(run func(ctx context.Context, key string, value V, report firehose.Report, ttl time.Duration)) *MockCacheStorage_Set_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 V
		if args[2] != nil {
			arg2 = args[2].(V)
		}
		var arg3 firehose.Report
		if args[3] != nil {
			arg3 = args[3].(firehose.Report)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockCacheStorage_Set_Call[V]) Return(report1 firehose.Report) *MockCacheStorage_Set_Call[V] {
	_c.Call.Return(report1)
	return _c
}

func (_c *MockCacheStorage_Set_Call[V]) RunAndReturn(run func(ctx context.Context, key string, value V, report firehose.Report, ttl time.Duration) firehose.Report) *MockCacheStorage_Set_Call[V] {
	_c.Call.Return(run)
	return _c
}
