// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package actions

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheStorage creates a new instance of MockCacheStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheStorage[O any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheStorage[O] {
	mock := &MockCacheStorage[O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheStorage is an autogenerated mock type for the CacheStorage type
type MockCacheStorage[O any] struct {
	mock.Mock
}

type MockCacheStorage_Expecter[O any] struct {
	mock *mock.Mock
}

func (_m *MockCacheStorage[O]) EXPECT() *MockCacheStorage_Expecter[O] {
	return &MockCacheStorage_Expecter[O]{mock: &_m.Mock}
}

// Get provides a mock function for the type MockCacheStorage
func (_mock *MockCacheStorage[O]) Get(ctx context.Context, key string) (O, bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 O
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (O, bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) O); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(O)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, key)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCacheStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCacheStorage_Get_Call[O any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheStorage_Expecter[O]) Get(ctx any, key any) *MockCacheStorage_Get_Call[O] {
	return &MockCacheStorage_Get_Call[O]{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockCacheStorage_Get_Call[O]) Run(run func(ctx context.Context, key string)) *MockCacheStorage_Get_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheStorage_Get_Call[O]) Return(v O, b bool, err error) *MockCacheStorage_Get_Call[O] {
	_c.Call.Return(v, b, err)
	return _c
}

func (_c *MockCacheStorage_Get_Call[O]) RunAndReturn(run func(ctx context.Context, key string) (O, bool, error)) *MockCacheStorage_Get_Call[O] {
	_c.Call.Return(run)
	return _c
}

// GetOrSet provides a mock function for the type MockCacheStorage
func (_mock *MockCacheStorage[O]) GetOrSet(ctx context.Context, key string, ttl time.Duration, cb func() (O, error)) (O, bool, error) {
	ret := _mock.Called(ctx, key, ttl, cb)

	if len(ret) == 0 {
		panic("no return value specified for GetOrSet")
	}

	var r0 O
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, func() (O, error)) (O, bool, error)); ok {
		return returnFunc(ctx, key, ttl, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, func() (O, error)) O); ok {
		r0 = returnFunc(ctx, key, ttl, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(O)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration, func() (O, error)) bool); ok {
		r1 = returnFunc(ctx, key, ttl, cb)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, time.Duration, func() (O, error)) error); ok {
		r2 = returnFunc(ctx, key, ttl, cb)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCacheStorage_GetOrSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrSet'
type MockCacheStorage_GetOrSet_Call[O any] struct {
	*mock.Call
}

// GetOrSet is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
//   - cb func() (O, error)
func (_e *MockCacheStorage_Expecter[O]) GetOrSet(ctx any, key any, ttl any, cb any) *MockCacheStorage_GetOrSet_Call[O] {
	return &MockCacheStorage_GetOrSet_Call[O]{Call: _e.mock.On("GetOrSet", ctx, key, ttl, cb)}
}

func (_c *MockCacheStorage_GetOrSet_Call[O]) Run(run func(ctx context.Context, key string, ttl time.Duration, cb func() (O, error))) *MockCacheStorage_GetOrSet_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 func() (O, error)
		if args[3] != nil {
			arg3 = args[3].(func() (O, error))
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCacheStorage_GetOrSet_Call[O]) Return(v O, b bool, err error) *MockCacheStorage_GetOrSet_Call[O] {
	_c.Call.Return(v, b, err)
	return _c
}

func (_c *MockCacheStorage_GetOrSet_Call[O]) RunAndReturn(run func(ctx context.Context, key string, ttl time.Duration, cb func() (O, error)) (O, bool, error)) *MockCacheStorage_GetOrSet_Call[O] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCacheStorage
func (_mock *MockCacheStorage[O]) Set(ctx context.Context, key string, ttl time.Duration, value O) error {
	ret := _mock.Called(ctx, key, ttl, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, O) error); ok {
		r0 = returnFunc(ctx, key, ttl, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheStorage_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCacheStorage_Set_Call[O any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
//   - value O
func (_e *MockCacheStorage_Expecter[O]) Set(ctx any, key any, ttl any, value any) *MockCacheStorage_Set_Call[O] {
	return &MockCacheStorage_Set_Call[O]{Call: _e.mock.On("Set", ctx, key, ttl, value)}
}

func (_c *MockCacheStorage_Set_Call[O]) Run(run func(ctx context.Context, key string, ttl time.Duration, value O)) *MockCacheStorage_Set_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 O
		if args[3] != nil {
			arg3 = args[3].(O)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCacheStorage_Set_Call[O]) Return(err error) *MockCacheStorage_Set_Call[O] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheStorage_Set_Call[O]) RunAndReturn(run func(ctx context.Context, key string, ttl time.Duration, value O) error) *MockCacheStorage_Set_Call[O] {
	_c.Call.Return(run)
	return _c
}
