// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package callbacks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskRunner creates a new instance of MockTaskRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRunner {
	mock := &MockTaskRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskRunner is an autogenerated mock type for the TaskRunner type
type MockTaskRunner struct {
	mock.Mock
}

type MockTaskRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRunner) EXPECT() *MockTaskRunner_Expecter {
	return &MockTaskRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockTaskRunner
func (_mock *MockTaskRunner) Run(fn func()) {
	_mock.Called(fn)
	return
}

// MockTaskRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTaskRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - fn func()
func (_e *MockTaskRunner_Expecter) Run(fn any) *MockTaskRunner_Run_Call {
	return &MockTaskRunner_Run_Call{Call: _e.mock.On("Run", fn)}
}

func (_c *MockTaskRunner_Run_Call) Run(run func(fn func())) *MockTaskRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func()
		if args[0] != nil {
			arg0 = args[0].(func())
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRunner_Run_Call) Return() *MockTaskRunner_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTaskRunner_Run_Call) RunAndReturn(run func(fn func())) *MockTaskRunner_Run_Call {
	_c.Run(run)
	return _c
}
